Category
DevIgork/BookStore pull request #11
Opened 2023-12-28 14:41 UTC by DevIgork

2023-12-28 16:51 UTC, vadymhrnk requested changes
Good job! Found some inconsistencies for you to consider

2023-12-28 16:51 UTC, vadymhrnk commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +        return categoryService.createBook(categoryDto);
Forgot to change the name of the method in `CategoryService` to `createCategory`

2023-12-28 16:51 UTC, vadymhrnk commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +    @PreAuthorize("hasAnyAuthority('ROLE_USER', 'ROLE_ADMIN')")
It's up to you, but this can be set only for `User` and you just need to add two roles to DB table for specified user

2023-12-28 16:51 UTC, vadymhrnk commented on src/main/java/com/example/bookstore/dto/category/CategoryResponseDto.java
> +public class CategoryResponseDto {
I believe that this class is the same as `CategoryDto`, and I don't get the point of this

2023-12-28 16:51 UTC, vadymhrnk commented on src/main/java/com/example/bookstore/mapper/CategoryMapper.java
> +    CategoryResponseDto toResponseDto(Category category);
As I mentioned, this method and `CategoryDto toDto(Category category)` is doing the same thing, I believe

2023-12-28 16:51 UTC, vadymhrnk commented on src/main/java/com/example/bookstore/model/Category.java
> +@Where(clause = "is_deleted=false")
`@Where` is deprecated. You can use `@SQLRestriction("is_deleted=false")` instead

2023-12-29 07:25 UTC, d1sam requested changes
good job, but some changes should be done!

2023-12-29 07:25 UTC, d1sam commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +    public CategoryDto createCategory(@RequestBody @Valid CreateCategoryRequestDto categoryDto) {
```suggestion
    @ResponseStatus(HttpStatus.CREATED)
    public CategoryDto createCategory(@RequestBody @Valid CreateCategoryRequestDto categoryDto) {
```

2023-12-29 07:25 UTC, d1sam commented on src/main/java/com/example/bookstore/mapper/CategoryMapper.java
> +@Component
```suggestion
```

2023-12-29 07:25 UTC, d1sam commented on src/main/java/com/example/bookstore/mapper/BookMapper.java
>  @Component
```suggestion
```

2023-12-29 07:25 UTC, d1sam commented on src/main/java/com/example/bookstore/model/Book.java
> +@SQLRestriction("is_deleted=false")
why did you change from `@Where`?

2023-12-29 07:25 UTC, d1sam commented on src/main/java/com/example/bookstore/model/Book.java
> +    private Set<Category> categories = new HashSet<>();
exclude from `equals/hashCode` and `toString`.

2023-12-29 07:25 UTC, d1sam commented on src/main/java/com/example/bookstore/model/Book.java
>  @Entity
```suggestion
@Entity
@NoArgsConstructor
```

2023-12-29 07:25 UTC, d1sam commented on src/main/java/com/example/bookstore/model/Category.java
> +    private String description;
```suggestion
    @Column
    private String description;
```

2023-12-29 07:25 UTC, d1sam commented on src/main/java/com/example/bookstore/model/Category.java
> +@SQLDelete(sql = "UPDATE categories SET is_deleted = true WHERE id=?")
```suggestion
@NoArgsConstructor
@SQLDelete(sql = "UPDATE categories SET is_deleted = true WHERE id=?")
```

2023-12-29 07:25 UTC, d1sam commented on src/main/java/com/example/bookstore/model/User.java
> +@SQLRestriction("is_deleted=false")
why?

2023-12-29 07:25 UTC, d1sam commented on src/main/java/com/example/bookstore/repository/BookRepository.java
>  public interface BookRepository extends JpaRepository<Book, Long>, JpaSpecificationExecutor<Book> {
```suggestion
@Repository
public interface BookRepository extends JpaRepository<Book, Long>, JpaSpecificationExecutor<Book> {
```

2023-12-29 07:25 UTC, d1sam commented on src/main/java/com/example/bookstore/repository/CategoryRepository.java
> +public interface CategoryRepository extends JpaRepository<Category, Long> {
```suggestion
@Repository
public interface CategoryRepository extends JpaRepository<Category, Long> {
```

2023-12-29 07:25 UTC, d1sam commented on src/main/resources/db/changelog/changes/10-create-categories-table.yaml
> +      author: Igor
```suggestion
      author: Igor Korolevich
```

2023-12-29 07:25 UTC, d1sam commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/14-insert-books_categories.yaml
```suggestion
      file: db/changelog/changes/14-insert-books_categories.yaml
      
```

2023-12-29 07:25 UTC, d1sam commented on src/main/resources/db/changelog/changes/11-create-books-categories-table.yaml
> +                    nullable: false
```suggestion
```
it's unnecessary, because you have `primary key`

2023-12-29 07:25 UTC, d1sam commented on src/main/resources/db/changelog/changes/11-create-books-categories-table.yaml
> +                    nullable: falsе
```suggestion
```
it's unnecessary, because you have `primary key`

2023-12-29 07:25 UTC, d1sam commented on src/main/resources/db/changelog/changes/10-create-categories-table.yaml
> +                    nullable: false
```suggestion
```
it's unnecessary, because you have `primary key`

2023-12-29 11:40 UTC, vovasalyha approved these changes

2024-01-02 12:42 UTC, merged