Card
DevIgork/BookStore pull request #12
Opened 2024-01-03 15:30 UTC by DevIgork

I know it's bad that the @transactional annotation is everywhere, I decided to fix it with all the problems that you may find

2024-01-03 21:08 UTC, nshtykh approved these changes
Great job!

2024-01-03 21:08 UTC, nshtykh commented on src/main/java/com/example/bookstore/dto/shopingcart/AddToCartRequestDto.java
> +    @NotNull
You can use @Positive here too

2024-01-04 08:58 UTC, d1sam requested changes
Good job, but there are some changes should be done!

2024-01-04 08:58 UTC, d1sam commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +    @PreAuthorize("hasAnyAuthority('ROLE_USER', 'ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasAnyAuthority('ROLE_USER')")
```

2024-01-04 08:58 UTC, d1sam commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +    @PreAuthorize("hasAnyAuthority('ROLE_USER', 'ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasAnyAuthority('ROLE_USER')")
```

2024-01-04 08:58 UTC, d1sam commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +    @PreAuthorize("hasAnyAuthority('ROLE_USER', 'ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasAnyAuthority('ROLE_USER')")
```

2024-01-04 08:58 UTC, d1sam commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +    @PreAuthorize("hasAnyAuthority('ROLE_USER', 'ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasAnyAuthority('ROLE_USER')")
```

2024-01-04 08:58 UTC, d1sam commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
Available endpoints for users with role ADMIN

- POST: /api/books/
- PUT: /api/books/{id}
- DELETE: /api/books/{id}
- POST: /api/categories
- PUT: /api/categories/{id}
- DELETE: /api/categories/{id}

2024-01-04 08:58 UTC, d1sam commented on src/main/java/com/example/bookstore/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-01-04 08:58 UTC, d1sam commented on src/main/java/com/example/bookstore/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-01-04 08:58 UTC, d1sam commented on src/main/java/com/example/bookstore/model/ShoppingCart.java
> +    @OneToOne
```suggestion
    @OneToOne(fetch = FetchType.LAZY)
```

2024-01-04 08:58 UTC, d1sam commented on src/main/java/com/example/bookstore/service/impl/ShopingCartServiceIml.java
> +    @Transactional
```suggestion
    @Transactional(readOnly = true)
```

2024-01-08 09:45 UTC, yevheniisynytsia approved these changes
:fire:

2024-02-04 17:54 UTC, merged