Order
DevIgork/BookStore pull request #13
Opened 2024-01-07 22:15 UTC by DevIgork

2024-01-08 21:15 UTC, Alexander1iubchenko approved these changes
Looks good to me. Good job

2024-01-09 08:43 UTC, yevheniisynytsia requested changes
Well done! Minor style comments left

2024-01-09 08:43 UTC, yevheniisynytsia commented on src/main/java/com/example/bookstore/model/OrderItem.java
> +    @JoinColumn(name = "order_id",nullable = false)
```suggestion
    @JoinColumn(name = "order_id", nullable = false)
```

2024-01-09 08:43 UTC, yevheniisynytsia commented on src/main/java/com/example/bookstore/model/OrderItem.java
> +    @JoinColumn(name = "book_id",nullable = false)
```suggestion
    @JoinColumn(name = "book_id", nullable = false)
```

2024-01-09 08:43 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/18-create-order-items-table.yaml
> +      id: create-orders-table
```suggestion
      id: create-order-items-table
```

2024-01-09 08:43 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/19-insert-user-roles-table.yaml
add empty line

2024-01-11 07:24 UTC, d1sam requested changes
Good job, but there are some minor changes should be done!

2024-01-11 07:24 UTC, d1sam commented on src/main/java/com/example/bookstore/controller/OrderController.java
> +            @RequestBody UpdateOrderStatusDto updateOrderStatusDto
```suggestion
            @RequestBody @Valid UpdateOrderStatusDto updateOrderStatusDto
```

2024-01-11 07:24 UTC, d1sam commented on src/main/java/com/example/bookstore/service/impl/OrderServiceImpl.java
> +        order.setStatus(Order.Status.valueOf(PENDING.name()));
```suggestion
        order.setStatus(PENDING);
```

2024-01-11 07:24 UTC, d1sam commented on src/main/java/com/example/bookstore/service/impl/OrderServiceImpl.java
> +    public OrderDto create(AddOrderRequestDto requestDto, Long userId) {
try to divide logic in this method to smaller private methods

2024-01-11 07:24 UTC, d1sam commented on src/main/java/com/example/bookstore/service/impl/OrderServiceImpl.java
> +                .map(orderMapper::toDto)
it's better to use method annotated as `@IterableMapping` inside mapper for mappings of `Iterable` objects

2024-01-15 06:56 UTC, yevheniisynytsia approved these changes
well done!

2024-02-04 17:55 UTC, merged