added some test form repository service, controller
DevIgork/BookStore pull request #16
Opened 2024-01-09 20:40 UTC by DevIgork

2024-01-09 21:31 UTC, DEz-1996 approved these changes
LGFM

2024-01-09 21:31 UTC, DEz-1996 commented on src/test/resources/database/shoppingCart/delete_all_cart_data.sql
> +DELETE FROM shopping_carts;
Add empty line)

2024-01-09 21:31 UTC, DEz-1996 commented on src/test/resources/database/shoppingCart/insert_into_shopping_carts.sql
> +VALUES (1);
Add empty line)

2024-01-10 08:30 UTC, yevheniisynytsia requested changes
Nice! Some comments left

2024-01-10 08:30 UTC, yevheniisynytsia commented on src/test/java/com/example/bookstore/controller/ShoppingCartControllerTest.java
> +            add to cart
```suggestion
            Add to cart, valid data
```
let's make names in such style to be more informative

2024-01-10 08:30 UTC, yevheniisynytsia commented on src/test/java/com/example/bookstore/service/ShoppingCartServiceTest.java
> +    private ShoppingCartServiceImpl cartService;
usually mock are defined first and then the service that you are testing with `@InjectMocks`

2024-01-10 08:30 UTC, yevheniisynytsia commented on src/test/java/com/example/bookstore/service/ShoppingCartServiceTest.java
> +            verify addToCart() method work
Add  cart item to shopping cart, valid data

2024-01-10 08:30 UTC, yevheniisynytsia commented on src/test/java/com/example/bookstore/service/ShoppingCartServiceTest.java
> +        when(bookRepository.findById(1L)).thenReturn(Optional.ofNullable(cleanCoder));
```suggestion

        when(bookRepository.findById(1L)).thenReturn(Optional.ofNullable(cleanCoder));
```

2024-01-10 08:30 UTC, yevheniisynytsia commented on src/test/java/com/example/bookstore/service/ShoppingCartServiceTest.java
> +        ShoppingCartDto actual = cartService.addToCart(requestDto, 1L);
```suggestion

        ShoppingCartDto actual = cartService.addToCart(requestDto, 1L);
```

2024-02-07 12:14 UTC, merged