Criteria query
DevIgork/BookStore pull request #4
Opened 2023-12-11 16:15 UTC by DevIgork

2023-12-12 10:27 UTC, d1sam requested changes
Well done, but please avoid String literals

2023-12-12 10:27 UTC, d1sam commented on src/main/java/com/example/bookstore/repository/impl/book/TitleSpecificationProvider.java
> +        return "title";
please avoid String literals

2023-12-12 10:27 UTC, d1sam commented on src/main/java/com/example/bookstore/repository/impl/book/AuthorSpecificationProvider.java
> +        return "author";
please avoid String literals

2023-12-13 07:15 UTC, kshuryhin requested changes
Good job, but there are some points to consider

2023-12-13 07:15 UTC, kshuryhin commented on src/main/java/com/example/bookstore/repository/impl/book/TitleSpecificationProvider.java
> +                -> root.get("title").in(Arrays.stream(params).toArray());
pay more attention, use constant here

2023-12-13 07:15 UTC, kshuryhin commented on src/main/java/com/example/bookstore/repository/impl/book/AuthorSpecificationProvider.java
> +                -> root.get("author").in(Arrays.stream(params).toArray());
pay more attention, use constant here

2023-12-13 07:15 UTC, kshuryhin commented on src/main/java/com/example/bookstore/repository/impl/BookSpecificationBuilder.java
> +        }
Could we split it to separate methods for better code readability?

2023-12-13 15:41 UTC, vovasalyha approved these changes
LGTM

2023-12-13 15:56 UTC, merged