added CustomGlobalExceptionHandler and some anotation
DevIgork/BookStore pull request #5
Opened 2023-12-15 11:49 UTC by DevIgork

2023-12-15 14:05 UTC, DPotapov93 approved these changes
Well done! 💪😎

2023-12-18 14:43 UTC, DEz-1996 approved these changes
Good job! But a few points to consider)

2023-12-18 14:43 UTC, DEz-1996 commented on src/main/java/com/example/bookstore/dto/CreateBookRequestDto.java
>      private String author;
Please consider the moment when the client will send an empty string, like title = "";

2023-12-18 14:43 UTC, DEz-1996 commented on src/main/java/com/example/bookstore/dto/CreateBookRequestDto.java
> +    @Size(min = 10, max = 13,message = " value can't be lower than 10 or more then 13")
ISBN is a standard that can have a length of 10 OR 13 digits

2023-12-19 08:48 UTC, bhdnchui requested changes
Good job! Just a few points to consider, also let's validate data in updateBook request.

2023-12-19 08:48 UTC, bhdnchui commented on src/main/java/com/example/bookstore/dto/CreateBookRequestDto.java
> +    @Min(0)
It would be better to use `@Positive` here.

2023-12-19 08:48 UTC, bhdnchui commented on src/main/java/com/example/bookstore/dto/CreateBookRequestDto.java
> +    @Pattern(regexp = "^(10|13)$", message = "value size must be 10 or 13")
Please, think about using org.hibernate.validator.constraints.ISBN annotation here.

2023-12-19 08:48 UTC, bhdnchui commented on src/main/java/com/example/bookstore/exception/CustomGlobalExceptionHandler.java
> +
I think you have exceptions that you are not handling here, so let's add handles for them here.

2023-12-19 13:36 UTC, vovasalyha requested changes
Good, but few more point need to be checked.

2023-12-19 13:36 UTC, vovasalyha commented on src/main/java/com/example/bookstore/dto/BookDto.java
> +    @NotBlank(message = "value can't be blank")
Take a look on this annotation documentation and decide if you still need to use NotNull along with NotBlank. Also, validate a maximum size of text fields to not exceed DB limitations.

2023-12-19 13:36 UTC, vovasalyha commented on src/main/java/com/example/bookstore/dto/BookDto.java
> +    @NotBlank(message = "value can't be blank")
NotBlank is redundant here, doesn't it?

2023-12-19 13:36 UTC, vovasalyha commented on src/main/java/com/example/bookstore/dto/BookDto.java
> +    @NotBlank(message = "value can't be blank")
NotBlank is redundant here, doesn't it?

2023-12-19 13:36 UTC, vovasalyha commented on src/main/java/com/example/bookstore/dto/BookDto.java
>  public class BookDto {
You don't need validation for this DTO as it is only used for returning of information from server, not for input (please apply below comments to CreateBookRequestDto

2023-12-20 08:19 UTC, bhdnchui approved these changes
Good job!

2023-12-23 14:22 UTC, merged