Jwt
DevIgork/BookStore pull request #9
Opened 2023-12-25 14:13 UTC by DevIgork

i moved some dto to user and book package

2023-12-26 10:11 UTC, d1sam requested changes
Good job,  but some minor change should be done!

2023-12-26 10:11 UTC, d1sam commented on src/main/java/com/example/bookstore/dto/user/UserLoginRequestDto.java
> +        @NotEmpty
```suggestion
        @NotBlank
```

2023-12-26 14:08 UTC, andrii-hoienko requested changes

2023-12-26 14:08 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("authorization");
Please don`t forget about constants

2023-12-26 14:08 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Please make "Bearer " constant

2023-12-26 14:08 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
magic number

2023-12-26 14:08 UTC, andrii-hoienko commented on pom.xml
>          <java.version>17</java.version>
Please resolve merge conflicts

2023-12-26 14:44 UTC, DevIgork reviewed
I will solve the merge config later with merges since in ide everything is ok there is just an empty line

2023-12-27 10:26 UTC, d1sam requested changes
Good job, some minor change should be done, and sorry, I can't approve with conflicts :(

2023-12-27 10:26 UTC, d1sam commented on src/main/resources/db/changelog/changes/07-insert-users-roles-table.yaml
it's better to add `PreConditions`, example:
  ```
    preConditions:
        - sqlCheck:
            expectedResult: 1
            sql: SELECT COUNT(*) FROM users WHERE email='admin@example.com'
        - sqlCheck:
            expectedResult: 1
            sql: SELECT COUNT(*) FROM roles WHERE name='ROLE_ADMIN'
      changes:
        - insert:
            tableName: user_role
            columns:
              - column:
                  name: user_id
                  valueComputed: (SELECT id FROM users WHERE email='admin@example.com')
              - column:
                  name: role_id
                  valueComputed: (SELECT id FROM roles WHERE name='ROLE_ADMIN')
```

2023-12-27 12:35 UTC, DevIgork reviewed
sorry forgot to change the name of the commit again, these commits on top are resore conflict

2023-12-27 15:39 UTC, vovasalyha approved these changes

2024-01-02 12:22 UTC, merged